version: '3.9'

services:

############################ RESTAURANT-MANAGEMENT-SERVICE ############################
  restaurant-db:
    container_name: restaurant-db
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_pwd
      POSTGRES_DB: restaurant
    volumes:
      - pg-restaurant-data:/var/lib/postgresql/data

  restaurant-service:
    container_name: restaurant-service
    build: 
      context: ./restaurant-management-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-db:5432/restaurant
      SPRING_DATASOURCE_USERNAME: restaurant_user
      SPRING_DATASOURCE_PASSWORD: restaurant_pwd
    depends_on:
      - restaurant-db

############################ ORDER-MANAGEMENT-SERVICE ############################
  order-db:
    container_name: order-db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pwd
      POSTGRES_DB: order
    volumes:
      - pg-order-data:/var/lib/postgresql/data

  order-service:
    container_name: order-service
    build: 
      context: ./order-management-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5433/order
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pwd
    depends_on:
      - order-db



volumes:
  pg-restaurant-data:
  pg-order-data: